# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Explore": "00_explore.ipynb"}

modules = ["explore.py"]

doc_url = "https://Aayush Agrawal.github.io/mlcookbooks/"

git_url = "https://github.com/Aayush Agrawal/mlcookbooks/tree/{branch}/"

def custom_doc_links(name): return None
